### ISSUE TITLE
"SpaceMouse Wireless" is listed twice

### ISSUE THREAD

**Issue by ruevs** [johnhw/pyspacenavigator#15]
Here:
https://github.com/johnhw/pyspacenavigator/blob/2ae9c5fbf5b5c3a2ac645d782e74d2a8df39e2ca/spacenavigator.py#L258
and here:
https://github.com/johnhw/pyspacenavigator/blob/2ae9c5fbf5b5c3a2ac645d782e74d2a8df39e2ca/spacenavigator.py#L343

Some more PIDs to add to the supported list (especially the wireless receiver dongles) can be found here:
https://3dconnexion.com/uk/support/faq/how-can-i-check-if-my-usb-3d-mouse-is-recognized-by-windows/

**Comment by ruevs** [comment]
The extra copy was inroduced here https://github.com/johnhw/pyspacenavigator/commit/93f2d7510afceb3e764b7bd0bc4d758b5877ec8b https://github.com/johnhw/pyspacenavigator/pull/14

**Comment by johnhw** [comment]
Fixed, thanks
