### ISSUE TITLE
pip not up to date

### ISSUE THREAD

**Issue by nextMJ** [johnhw/pyspacenavigator#19]
When installing via `pip` (https://pypi.org/project/spacenavigator/), the package is not up to date and thus, not working correctly. I would like to help fixing it but do not have idea how.

**Comment by tudor-manole** [comment]
Yeah, same issue. I just installed from pip and it's missing things that are now current in this repo.

**Comment by connorjak** [comment]
Still same issue; pip package is from 2019. It works fine for SpaceNavigator but doesn't include support for further devices that work in the source version here.

**Comment by johnhw** [comment]
Pip should be up-to-date now.
