### ISSUE TITLE
web app and pyspacenavigator

### ISSUE THREAD

**Issue by silvius76** [johnhw/pyspacenavigator#2]
Hi,

In your opinion is possible use library in framework like flask, django, pyramid ?
I'd use it in my web app

Thanks

**Comment by johnhw** [comment]
Probably, but I don't think it would do what you want -- the library needs
to be running on a local machine to access USB and talk to the
spacenavigator device.

So while you could certainly add it to a server and control a
locally-served webpage via the 3D device, you couldn't use as a way to
access a 3D device on a remote client.

--John
